---
:date:
  :date: Date
  :parse: '<%= "#{date[:date]}" %>'
:user:
  :first_name: Unknown
  :last_name: Observer
:observation:
  :latitude: LATdm
  :longitude: LONdm
  :ice_attributes:
    :total_concentration: TC
    :thick_ice_lookup_code: TH
    :thin_ice_lookup_code: OT
    :open_water_lookup_code: OW
  :ice_observations_attributes:
    -
      :obs_type: PrimaryObsType
      :partial_concentration: PrimaryC
      :ice_lookup_code: PrimaryT
      :thickness: PrimaryZ
      :floe_size_lookup_code: PrimaryF
      :topography_attributes:
        :topography_lookup_code: PrimaryTopography
        :old: PrimaryOld
        :consolidated: PrimaryConsolidated
        :concentration: PrimaryConcentration
        :ridge_height: PrimaryRidgeHeight
      :sediment_lookup_code: PrimarySD
      :biota_lookup_code: PrimaryAL
      :snow_lookup_code: PrimarySY
      :snow_thickness: PrimarySH
      :melt_pond_attributes:
        :surface_coverage: PrimarySurfaceCoverage
        :max_depth_lookup_code: PrimaryMaxDepth
        :pattern_lookup_code: PrimaryPattern
        :surface_lookup_code: PrimarySurface
        :freeboard: PrimaryFreeboard
    -
      :obs_type: SecondaryObsType
      :partial_concentration: SecondaryC
      :ice_lookup_code: SecondaryT
      :thickness: SecondaryZ
      :floe_size_lookup_code: SecondaryF
      :topography_attributes:
        :topography_lookup_code: SecondaryTopography
        :old: SecondaryOld
        :consolidated: SecondaryConsolidated
        :concentration: SecondaryConcentration
        :ridge_height: SecondaryRidgeHeight
      :sediment_lookup_code: SecondarySD
      :biota_lookup_code: SecondaryAL
      :snow_lookup_code: SecondarySY
      :snow_thickness: SecondarySH
      :melt_pond_attributes:
        :surface_coverage: SecondarySurfaceCoverage
        :max_depth_lookup_code: SecondaryMaxDepth
        :pattern_lookup_code: SecondaryPattern
        :surface_lookup_code: SecondarySurface
        :freeboard: SecondaryFreeboard
    -
      :obs_type: TertiaryObsType
      :partial_concentration: TertiaryC
      :ice_lookup_code: TertiaryT
      :thickness: TertiaryZ
      :floe_size_lookup_code: TertiaryF
      :topography_attributes:
        :topography_lookup_code: TertiaryTopography
        :old: TertiaryOld
        :consolidated: TertiaryConsolidated
        :concentration: TertiaryConcentration
        :ridge_height: TertiaryRidgeHeight
      :sediment_lookup_code: TertiarySD
      :biota_lookup_code: TertiaryAL
      :snow_lookup_code: TertiarySY
      :snow_thickness: TertiarySH
      :melt_pond_attributes:
        :surface_coverage: TertiarySurfaceCoverage
        :max_depth_lookup_code: TertiaryMaxDepth
        :pattern_lookup_code: TertiaryPattern
        :surface_lookup_code: TertiarySurface
        :freeboard: TertiaryFreeboard
  :meteorology_attributes:
    :visibility_lookup_code: Visibility
    :weather_lookup_code: Weather
    :clouds_attributes:
      -
        :cloud_type: HighCloudType
        :cover: HighCover
        :height: HighHeight
        :cloud_lookup_code: HighCloud
      -
        :cloud_type: MediumCloudType
        :cover: MediumCover
        :height: MediumHeight
        :cloud_lookup_code: MediumCloud
      -
        :cloud_type: LowCloudType
        :cover: LowCover
        :height: LowHeight
        :cloud_lookup_code: LowCloud